In [1]:
import numpy as np
import os
import pysynphot as s

/home/mldantas/miniconda2/lib/python2.7/site-packages/pysynphot/locations.py:44: UserWarning: PYSYN_CDBS is undefined; functionality will be SEVERELY crippled.
  warnings.warn("PYSYN_CDBS is undefined; functionality will be SEVERELY "
/home/mldantas/miniconda2/lib/python2.7/site-packages/pysynphot/locations.py:119: UserWarning: Extinction files should be moved to $PYSYN_CDBS/extinction for compatibility with future versions of pysynphot.
  warnings.warn('Extinction files should be moved to '
/home/mldantas/miniconda2/lib/python2.7/site-packages/pysynphot/locations.py:155: UserWarning: Extinction files not found in grid/extinction
  warnings.warn('Extinction files not found in %s' % (extdir,))
/home/mldantas/miniconda2/lib/python2.7/site-packages/pysynphot/locations.py:133: UserWarning: PYSYN_CDBS is undefined; cannot find mtab/*_tmg.fits file
  warnings.warn("PYSYN_CDBS is undefined; cannot find %s file" % template)
/home/mldantas/miniconda2/lib/python2.7/site-packages/pysynphot/locati

In [2]:
jpas_filters_path = '/home/mldantas/Dropbox/DoutoradoIAG/Challenge/Filters/JPAS_filters'
test_specs        = '/home/mldantas/Dropbox/DoutoradoIAG/Challenge/Sanity_Check/Specs'
jpas_filters_list = np.loadtxt('/home/mldantas/Dropbox/DoutoradoIAG/Challenge/Filters/jpas_filters_list.txt', dtype=str)
specs_list        = np.loadtxt('/home/mldantas/Dropbox/DoutoradoIAG/Challenge/Sanity_Check/specslist.txt', dtype=str)

In [3]:
# Constants --------------------------------------------------------------------------------------------------------
c = 2.99792458E18                  # Light Speed in Angstrom s^-1

In [ ]:
for each_spectrum in specs_list:
    # Transforming the specs from f_lambda to f_nu -----------------------------------------------------------------
    wavelength = np.loadtxt(os.path.join(test_specs, each_spectrum), usecols=[0])
    f_lambda   = np.loadtxt(os.path.join(test_specs, each_spectrum), usecols=[1])
    for jpas_filters in jpas_filters_list:
        filter_name          = jpas_filters.split('.')[0]
        jpas_filter_bandpass = np.array(np.loadtxt(os.path.join(jpas_filters_path, jpas_filters)))
#         jpas_filter_bandpass = s.FileBandpass(jpas_filter_bandpass)
        sdss_spectrum        = np.loadtxt(os.path.join(test_specs, each_spectrum), usecols=(0,1))
        print sdss_spectrum
        exit()
#         sdss_spectrum        = s.FileSpectrum(sdss_spectrum)
#         photometry           = s.Observation(sdss_spectrum, jpas_filter_bandpass, binset=np.arange(3000, 11000, 1))

[[ 3200.     0.]
 [ 3201.     0.]
 [ 3202.     0.]
 ..., 
 [ 9198.     0.]
 [ 9199.     0.]
 [ 9200.     0.]]
[[ 3200.     0.]
 [ 3201.     0.]
 [ 3202.     0.]
 ..., 
 [ 9198.     0.]
 [ 9199.     0.]
 [ 9200.     0.]]
[[ 3200.     0.]
 [ 3201.     0.]
 [ 3202.     0.]
 ..., 
 [ 9198.     0.]
 [ 9199.     0.]
 [ 9200.     0.]]
[[ 3200.     0.]
 [ 3201.     0.]
 [ 3202.     0.]
 ..., 
 [ 9198.     0.]
 [ 9199.     0.]
 [ 9200.     0.]]
[[ 3200.     0.]
 [ 3201.     0.]
 [ 3202.     0.]
 ..., 
 [ 9198.     0.]
 [ 9199.     0.]
 [ 9200.     0.]]
[[ 3200.     0.]
 [ 3201.     0.]
 [ 3202.     0.]
 ..., 
 [ 9198.     0.]
 [ 9199.     0.]
 [ 9200.     0.]]
[[ 3200.     0.]
 [ 3201.     0.]
 [ 3202.     0.]
 ..., 
 [ 9198.     0.]
 [ 9199.     0.]
 [ 9200.     0.]]
[[ 3200.     0.]
 [ 3201.     0.]
 [ 3202.     0.]
 ..., 
 [ 9198.     0.]
 [ 9199.     0.]
 [ 9200.     0.]]
[[ 3200.     0.]
 [ 3201.     0.]
 [ 3202.     0.]
 ..., 
 [ 9198.     0.]
 [ 9199.     0.]
 [ 9200.     0.]]
[[ 3200.  